### ISSUE TITLE
wPopup.showAtFingerLocation(WPopupDirection.RIGHT_TOP)

### ISSUE THREAD

**Issue by meiniepan** [wanglu1209/WPopup#2]
![_20180930102326](https://user-images.githubusercontent.com/7891972/46252497-d08f0480-c458-11e8-9673-5706038d7ae6.jpg)
pop跳出来位置随机的呀，不稳定，而且偏离有点大，能不能调的近点？

**Comment by wanglu1209** [comment]
你调用的这个方法是根据手指来弹出pop的，如果想要在圆点上，要用showAtDirectionByView(view, WPopupDirection.TOP)

**Comment by wanglu1209** [comment]
还有问题吗？没有的话关了啊

**Comment by meiniepan** [comment]
谢谢，没了
