### ISSUE TITLE
不能添加自定义View？？？ setView方法也没有？

### ISSUE THREAD

**Issue by CordyHo** [wanglu1209/WPopup#6]
不能添加自定义View？？？ setView方法也没有？

**Comment by wanglu1209** [comment]
可以自己定义view
![image](https://user-images.githubusercontent.com/17212822/50323242-b3c41380-0513-11e9-9378-7d044f7aabf4.png)

**Comment by CordyHo** [comment]
好麻烦，就不能直接链式setView()吗

**Comment by wanglu1209** [comment]
不能，因为这和我最开始的初衷就不一样。
而且这样也不麻烦，通用的方法我都封装好了。

**Comment by CordyHo** [comment]
而且传入一个一个layoutRes有什么用？ 怎么操作里面的View

**Comment by wanglu1209** [comment]
使用getContentView方法可以获取到View
